[package]
name = "bevy_network_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = {path = "./server"}
common = {path = "./common"}
client = {path = "./client"}